//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.GeneralMessages", typeof(GeneralMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales Incorrectas..
        /// </summary>
        public static string BadCredentials {
            get {
                return ResourceManager.GetString("BadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible conectarse con Meta, por favor verifica las credenciales o disponibilidad.
        /// </summary>
        public static string BadMetaCredential {
            get {
                return ResourceManager.GetString("BadMetaCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible conectarse con NetSuite, por favor verifica las credenciales o disponibilidad.
        /// </summary>
        public static string BadNetSuiteCredentials {
            get {
                return ResourceManager.GetString("BadNetSuiteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión del archivo:  {0}  no permitido, extensiones válidas: [{1}].
        /// </summary>
        public static string DenegadeFileExtension {
            get {
                return ResourceManager.GetString("DenegadeFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual, es igual a la nueva contraseña. Por favor asignar contraseñas diferentes..
        /// </summary>
        public static string EqualCredentials {
            get {
                return ResourceManager.GetString("EqualCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autenticado correctamente.
        /// </summary>
        public static string Error401 {
            get {
                return ResourceManager.GetString("Error401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno, por favor vuelva a intentarlo..
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno..
        /// </summary>
        public static string Error5001 {
            get {
                return ResourceManager.GetString("Error5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe, por favor asignar otro.
        /// </summary>
        public static string ExistingName {
            get {
                return ResourceManager.GetString("ExistingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del proyecto [{0}] ya se encuentra registrado, asociado al  [{1}].
        /// </summary>
        public static string ExistingProjectName {
            get {
                return ResourceManager.GetString("ExistingProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo [{0}] es obligatorio..
        /// </summary>
        public static string FieldMandatory {
            get {
                return ResourceManager.GetString("FieldMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sincronización ha finalizado.
        /// </summary>
        public static string FinishedSyncing {
            get {
                return ResourceManager.GetString("FinishedSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inactivo, por favor contactar a un administrador..
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email: [{0}] no es válido..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro eliminado exitosamente..
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] ya se encuentra registrado..
        /// </summary>
        public static string ItemDuplicate {
            get {
                return ResourceManager.GetString("ItemDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro guardado exitosamente..
        /// </summary>
        public static string ItemInserted {
            get {
                return ResourceManager.GetString("ItemInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible eliminar el registro, por favor intentalo de nuevo..
        /// </summary>
        public static string ItemNoDeleted {
            get {
                return ResourceManager.GetString("ItemNoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] no encontrado, por favor verificar los registros enviados..
        /// </summary>
        public static string ItemNoFound {
            get {
                return ResourceManager.GetString("ItemNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible guardar el registro, por favor intentalo de nuevo..
        /// </summary>
        public static string ItemNoInserted {
            get {
                return ResourceManager.GetString("ItemNoInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible actualizar el registro, por favor intentalo de nuevo..
        /// </summary>
        public static string ItemNoUpdated {
            get {
                return ResourceManager.GetString("ItemNoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro actualizado exitosamente..
        /// </summary>
        public static string ItemUpdated {
            get {
                return ResourceManager.GetString("ItemUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡El tamaño del archivo es demasiado grande! [máximo {0} MB].
        /// </summary>
        public static string MaxSizeFile {
            get {
                return ResourceManager.GetString("MaxSizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actualizada exitosamente..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al cambiar la contraseña..
        /// </summary>
        public static string PasswordChangeError {
            get {
                return ResourceManager.GetString("PasswordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña reseteada exitosamente..
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Correo ya se encentra registrado en nuestro sistema, por favor usar otro..
        /// </summary>
        public static string RegisteredEmail {
            get {
                return ResourceManager.GetString("RegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una sincronización en proceso.
        /// </summary>
        public static string SyncingInProcess {
            get {
                return ResourceManager.GetString("SyncingInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error con las credenciales.
        /// </summary>
        public static string SyncingWithProblems {
            get {
                return ResourceManager.GetString("SyncingWithProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema guardado exitosamente..
        /// </summary>
        public static string ThemeSaveSuccess {
            get {
                return ResourceManager.GetString("ThemeSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al guardar el configuración del tema, por favor volver a intentarlo..
        /// </summary>
        public static string ThmeSaveFaile {
            get {
                return ResourceManager.GetString("ThmeSaveFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permisos para ejecutar esta operación.
        /// </summary>
        public static string WithoutPermission {
            get {
                return ResourceManager.GetString("WithoutPermission", resourceCulture);
            }
        }
    }
}
